services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: sector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2

    ports:
      - "5433:5432"
    restart: always

  web:
    build: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000 & python main.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always